name: API Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes de API
      run: npm test
      continue-on-error: true

    - name: Publicar Sumário 
      uses: matt-ball/jest-stare-action@v2
      if: always()
      with:
        json-file: ./reports/test-report.json

    - name: Upload do Relatório em HTML
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-test-report
        path: reports/test-report.html
